# Generated by Django 5.1.3 on 2024-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('email', models.CharField(db_collation='utf8mb4_0900_ai_ci', default=None, max_length=50, null=True)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
                ('password', models.CharField(default=None, max_length=100, null=True)),
                ('gender', models.CharField(default=None, max_length=10, null=True)),
                ('dob', models.DateTimeField(default=None, null=True)),
                ('avatar_id', models.BigIntegerField(default=None, null=True)),
                ('image_data', models.TextField()),
                ('first_signup_mail', models.SmallIntegerField(default=1)),
                ('is_active', models.SmallIntegerField(default=None, null=True)),
                ('is_deleted', models.SmallIntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
