# Generated by Django 5.1.3 on 2024-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='first_signup_mail',
            field=models.SmallIntegerField(default='1'),
        ),
    ]
