# Generated by Django 5.1.3 on 2024-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_users_user_id_alter_users_first_signup_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_signup_mail',
            field=models.SmallIntegerField(default=1),
        ),
    ]
