# Generated by Django 5.1.3 on 2024-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_users_is_active_alter_users_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_signup_mail',
            field=models.BooleanField(default=1),
        ),
    ]
