# Generated by Django 5.1.3 on 2024-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_users_email_alter_users_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
